import { Module, VuexModule, VuexMutation } from 'nuxt-property-decorator'
import { IFuncionario } from '~/types/IFuncionario'

@Module({
  name: 'funcionarios',
  namespaced: true,
  stateFactory: true,
})
export default class FuncionariosModule extends VuexModule {
  funcionarios: IFuncionario[] = [
    {
      id: 1,
      nome: 'Cynthia',
      sobrenome: 'Grimes',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'Pagamento',
      contratado: 16,
    },
    {
      id: 2,
      nome: 'Ivor',
      sobrenome: 'Owens',
      cargo: 'Desenvolvedor Front-End Pleno',
      setor: 'Produto',
      contratado: 29,
    },
    {
      id: 3,
      nome: 'Reed',
      sobrenome: 'Frederick',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'Produto',
      contratado: 42,
    },
    {
      id: 4,
      nome: 'Ina',
      sobrenome: 'Baker',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'API',
      contratado: 32,
    },
    {
      id: 5,
      nome: 'Kermit',
      sobrenome: 'Morris',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Pagamento',
      contratado: 9,
    },
    {
      id: 6,
      nome: 'Ryder',
      sobrenome: 'Patterson',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Componentes',
      contratado: 44,
    },
    {
      id: 7,
      nome: 'Brent',
      sobrenome: 'Klein',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Produto',
      contratado: 9,
    },
    {
      id: 8,
      nome: 'Jillian',
      sobrenome: 'Moss',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Produto',
      contratado: 40,
    },
    {
      id: 9,
      nome: 'Shafira',
      sobrenome: 'Rocha',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Pagamento',
      contratado: 42,
    },
    {
      id: 10,
      nome: 'Philip',
      sobrenome: 'Leach',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Componentes',
      contratado: 22,
    },
    {
      id: 11,
      nome: 'Lisandra',
      sobrenome: 'Guy',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Componentes',
      contratado: 46,
    },
    {
      id: 12,
      nome: 'Jillian',
      sobrenome: 'Henderson',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'Pagamento',
      contratado: 22,
    },
    {
      id: 13,
      nome: 'Clark',
      sobrenome: 'Carrillo',
      cargo: 'Desenvolvedor Back-End Pleno',
      setor: 'Pagamento',
      contratado: 43,
    },
    {
      id: 14,
      nome: 'Myles',
      sobrenome: 'Kerr',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Componentes',
      contratado: 43,
    },
    {
      id: 15,
      nome: 'Charles',
      sobrenome: 'Carr',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Componentes',
      contratado: 2,
    },
    {
      id: 16,
      nome: 'Bernard',
      sobrenome: 'Rush',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'API',
      contratado: 33,
    },
    {
      id: 17,
      nome: 'Ulysses',
      sobrenome: 'Collins',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'API',
      contratado: 45,
    },
    {
      id: 18,
      nome: 'Macaulay',
      sobrenome: 'Perez',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Pagamento',
      contratado: 40,
    },
    {
      id: 19,
      nome: 'Anika',
      sobrenome: 'Cobb',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'Produto',
      contratado: 41,
    },
    {
      id: 20,
      nome: 'Cyrus',
      sobrenome: 'Dean',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Componentes',
      contratado: 27,
    },
    {
      id: 21,
      nome: 'Rashad',
      sobrenome: 'Nash',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Componentes',
      contratado: 8,
    },
    {
      id: 22,
      nome: 'Delilah',
      sobrenome: 'Whitehead',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Pagamento',
      contratado: 33,
    },
    {
      id: 23,
      nome: 'Kato',
      sobrenome: 'Fischer',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'API',
      contratado: 24,
    },
    {
      id: 24,
      nome: 'Quynn',
      sobrenome: 'Webster',
      cargo: 'Desenvolvedor Front-End Pleno',
      setor: 'Componentes',
      contratado: 41,
    },
    {
      id: 25,
      nome: 'Catherine',
      sobrenome: 'Chapman',
      cargo: 'Desenvolvedor Back-End Júnior',
      setor: 'API',
      contratado: 24,
    },
    {
      id: 26,
      nome: 'Baker',
      sobrenome: 'Mcleod',
      cargo: 'Desenvolvedor Back-End Júnior',
      setor: 'API',
      contratado: 27,
    },
    {
      id: 27,
      nome: 'Maris',
      sobrenome: 'Castaneda',
      cargo: 'Desenvolvedor Front-End Pleno',
      setor: 'Produto',
      contratado: 16,
    },
    {
      id: 28,
      nome: 'Velma',
      sobrenome: 'Steele',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Componentes',
      contratado: 24,
    },
    {
      id: 29,
      nome: 'Hanna',
      sobrenome: 'Meyers',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Pagamento',
      contratado: 31,
    },
    {
      id: 30,
      nome: 'Paula',
      sobrenome: 'Carver',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Pagamento',
      contratado: 13,
    },
    {
      id: 31,
      nome: 'Anjolie',
      sobrenome: 'Mcintosh',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Produto',
      contratado: 30,
    },
    {
      id: 32,
      nome: 'Angelica',
      sobrenome: 'Hurst',
      cargo: 'Desenvolvedor Back-End Júnior',
      setor: 'Produto',
      contratado: 24,
    },
    {
      id: 33,
      nome: 'Herman',
      sobrenome: 'Stark',
      cargo: 'Desenvolvedor Back-End Júnior',
      setor: 'Produto',
      contratado: 14,
    },
    {
      id: 34,
      nome: 'Brady',
      sobrenome: 'Skinner',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'API',
      contratado: 45,
    },
    {
      id: 35,
      nome: 'Wayne',
      sobrenome: 'Duran',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'Pagamento',
      contratado: 17,
    },
    {
      id: 36,
      nome: 'Mohammad',
      sobrenome: 'Hewitt',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'API',
      contratado: 2,
    },
    {
      id: 37,
      nome: 'Mona',
      sobrenome: 'Tate',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'Produto',
      contratado: 18,
    },
    {
      id: 38,
      nome: 'Gage',
      sobrenome: 'Knox',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Pagamento',
      contratado: 6,
    },
    {
      id: 39,
      nome: 'Wynter',
      sobrenome: 'Dominguez',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Componentes',
      contratado: 25,
    },
    {
      id: 40,
      nome: 'Joan',
      sobrenome: 'Macias',
      cargo: 'Lead Tech',
      setor: 'Componentes',
      contratado: 17,
    },
    {
      id: 41,
      nome: 'Ramona',
      sobrenome: 'Bradley',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'API',
      contratado: 1,
    },
    {
      id: 42,
      nome: 'Armand',
      sobrenome: 'Leblanc',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Pagamento',
      contratado: 19,
    },
    {
      id: 43,
      nome: 'Elmo',
      sobrenome: 'Shaw',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Produto',
      contratado: 10,
    },
    {
      id: 44,
      nome: 'Wayne',
      sobrenome: 'Jordan',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Pagamento',
      contratado: 2,
    },
    {
      id: 45,
      nome: 'Dieter',
      sobrenome: 'Logan',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Componentes',
      contratado: 4,
    },
    {
      id: 46,
      nome: 'Daphne',
      sobrenome: 'Roy',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'Componentes',
      contratado: 23,
    },
    {
      id: 47,
      nome: 'Hayley',
      sobrenome: 'Guzman',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Pagamento',
      contratado: 39,
    },
    {
      id: 48,
      nome: 'Emily',
      sobrenome: 'Browning',
      cargo: 'Desenvolvedor Back-End Pleno',
      setor: 'Componentes',
      contratado: 21,
    },
    {
      id: 49,
      nome: 'Desirae',
      sobrenome: 'Santos',
      cargo: 'Lead Tech',
      setor: 'API',
      contratado: 13,
    },
    {
      id: 50,
      nome: 'Brenda',
      sobrenome: 'Rush',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'API',
      contratado: 33,
    },
  ]

  @VuexMutation
  ADICIONA_FUNCIONARIO(funcionario: IFuncionario) {
    this.funcionarios.push(funcionario)
  }

  @VuexMutation
  DELETE_FUNCIONARIO(id: number) {
    this.funcionarios = this.funcionarios.filter((f) => f.id !== id)
  }
}
