import { Vue, Component } from 'nuxt-property-decorator'
import { IUsuario } from '~/types/IUsuario'

@Component
export class FuncionariosMixin extends Vue {
  funcionarios: IUsuario[] = [
    {
      nome: 'Cynthia',
      sobrenome: 'Grimes',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'Pagamento',
      contratado: 16,
    },
    {
      nome: 'Ivor',
      sobrenome: 'Owens',
      cargo: 'Desenvolvedor Front-End Pleno',
      setor: 'Produto',
      contratado: 29,
    },
    {
      nome: 'Reed',
      sobrenome: 'Frederick',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'Produto',
      contratado: 42,
    },
    {
      nome: 'Ina',
      sobrenome: 'Baker',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'API',
      contratado: 32,
    },
    {
      nome: 'Kermit',
      sobrenome: 'Morris',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Pagamento',
      contratado: 9,
    },
    {
      nome: 'Ryder',
      sobrenome: 'Patterson',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Componentes',
      contratado: 44,
    },
    {
      nome: 'Brent',
      sobrenome: 'Klein',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Produto',
      contratado: 9,
    },
    {
      nome: 'Jillian',
      sobrenome: 'Moss',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Produto',
      contratado: 40,
    },
    {
      nome: 'Shafira',
      sobrenome: 'Rocha',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Pagamento',
      contratado: 42,
    },
    {
      nome: 'Philip',
      sobrenome: 'Leach',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Componentes',
      contratado: 22,
    },
    {
      nome: 'Lisandra',
      sobrenome: 'Guy',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Componentes',
      contratado: 46,
    },
    {
      nome: 'Jillian',
      sobrenome: 'Henderson',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'Pagamento',
      contratado: 22,
    },
    {
      nome: 'Clark',
      sobrenome: 'Carrillo',
      cargo: 'Desenvolvedor Back-End Pleno',
      setor: 'Pagamento',
      contratado: 43,
    },
    {
      nome: 'Myles',
      sobrenome: 'Kerr',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Componentes',
      contratado: 43,
    },
    {
      nome: 'Charles',
      sobrenome: 'Carr',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Componentes',
      contratado: 2,
    },
    {
      nome: 'Bernard',
      sobrenome: 'Rush',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'API',
      contratado: 33,
    },
    {
      nome: 'Ulysses',
      sobrenome: 'Collins',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'API',
      contratado: 45,
    },
    {
      nome: 'Macaulay',
      sobrenome: 'Perez',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Pagamento',
      contratado: 40,
    },
    {
      nome: 'Anika',
      sobrenome: 'Cobb',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'Produto',
      contratado: 41,
    },
    {
      nome: 'Cyrus',
      sobrenome: 'Dean',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Componentes',
      contratado: 27,
    },
    {
      nome: 'Rashad',
      sobrenome: 'Nash',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Componentes',
      contratado: 8,
    },
    {
      nome: 'Delilah',
      sobrenome: 'Whitehead',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Pagamento',
      contratado: 33,
    },
    {
      nome: 'Kato',
      sobrenome: 'Fischer',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'API',
      contratado: 24,
    },
    {
      nome: 'Quynn',
      sobrenome: 'Webster',
      cargo: 'Desenvolvedor Front-End Pleno',
      setor: 'Componentes',
      contratado: 41,
    },
    {
      nome: 'Catherine',
      sobrenome: 'Chapman',
      cargo: 'Desenvolvedor Back-End Júnior',
      setor: 'API',
      contratado: 24,
    },
    {
      nome: 'Baker',
      sobrenome: 'Mcleod',
      cargo: 'Desenvolvedor Back-End Júnior',
      setor: 'API',
      contratado: 27,
    },
    {
      nome: 'Maris',
      sobrenome: 'Castaneda',
      cargo: 'Desenvolvedor Front-End Pleno',
      setor: 'Produto',
      contratado: 16,
    },
    {
      nome: 'Velma',
      sobrenome: 'Steele',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Componentes',
      contratado: 24,
    },
    {
      nome: 'Hanna',
      sobrenome: 'Meyers',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Pagamento',
      contratado: 31,
    },
    {
      nome: 'Paula',
      sobrenome: 'Carver',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Pagamento',
      contratado: 13,
    },
    {
      nome: 'Anjolie',
      sobrenome: 'Mcintosh',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Produto',
      contratado: 30,
    },
    {
      nome: 'Angelica',
      sobrenome: 'Hurst',
      cargo: 'Desenvolvedor Back-End Júnior',
      setor: 'Produto',
      contratado: 24,
    },
    {
      nome: 'Herman',
      sobrenome: 'Stark',
      cargo: 'Desenvolvedor Back-End Júnior',
      setor: 'Produto',
      contratado: 14,
    },
    {
      nome: 'Brady',
      sobrenome: 'Skinner',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'API',
      contratado: 45,
    },
    {
      nome: 'Wayne',
      sobrenome: 'Duran',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'Pagamento',
      contratado: 17,
    },
    {
      nome: 'Mohammad',
      sobrenome: 'Hewitt',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'API',
      contratado: 2,
    },
    {
      nome: 'Mona',
      sobrenome: 'Tate',
      cargo: 'Desenvolvedor Full-Stack Sênior',
      setor: 'Produto',
      contratado: 18,
    },
    {
      nome: 'Gage',
      sobrenome: 'Knox',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Pagamento',
      contratado: 6,
    },
    {
      nome: 'Wynter',
      sobrenome: 'Dominguez',
      cargo: 'Desenvolvedor Front-End Sênior',
      setor: 'Componentes',
      contratado: 25,
    },
    {
      nome: 'Joan',
      sobrenome: 'Macias',
      cargo: 'Lead Tech',
      setor: 'Componentes',
      contratado: 17,
    },
    {
      nome: 'Ramona',
      sobrenome: 'Bradley',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'API',
      contratado: 1,
    },
    {
      nome: 'Armand',
      sobrenome: 'Leblanc',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Pagamento',
      contratado: 19,
    },
    {
      nome: 'Elmo',
      sobrenome: 'Shaw',
      cargo: 'Desenvolvedor Front-End Júnior',
      setor: 'Produto',
      contratado: 10,
    },
    {
      nome: 'Wayne',
      sobrenome: 'Jordan',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Pagamento',
      contratado: 2,
    },
    {
      nome: 'Dieter',
      sobrenome: 'Logan',
      cargo: 'Desenvolvedor Full-Stack Pleno',
      setor: 'Componentes',
      contratado: 4,
    },
    {
      nome: 'Daphne',
      sobrenome: 'Roy',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'Componentes',
      contratado: 23,
    },
    {
      nome: 'Hayley',
      sobrenome: 'Guzman',
      cargo: 'Desenvolvedor Full-Stack Júnior',
      setor: 'Pagamento',
      contratado: 39,
    },
    {
      nome: 'Emily',
      sobrenome: 'Browning',
      cargo: 'Desenvolvedor Back-End Pleno',
      setor: 'Componentes',
      contratado: 21,
    },
    {
      nome: 'Desirae',
      sobrenome: 'Santos',
      cargo: 'Lead Tech',
      setor: 'API',
      contratado: 13,
    },
    {
      nome: 'Brenda',
      sobrenome: 'Rush',
      cargo: 'Desenvolvedor Back-End Sênior',
      setor: 'API',
      contratado: 33,
    },
  ]
}
