import { EmployeesDTO } from "./dashboard-list/dto/employees.dto";

export const employeesMock: EmployeesDTO[] = [{"id":1,"name":"Sallie","surname":"Langfield","position":"Help Desk Operator","departament":"Accounting","date":"28/08/2020"},
{"id":2,"name":"Torrance","surname":"Mougel","position":"Librarian","departament":"Accounting","date":"25/02/2020"},
{"id":3,"name":"Ginevra","surname":"Copley","position":"Internal Auditor","departament":"Accounting","date":"10/03/2019"},
{"id":4,"name":"Melinda","surname":"Dabbes","position":"Project Manager","departament":"Accounting","date":"02/11/2020"},
{"id":5,"name":"Karna","surname":"Beddon","position":"Staff Scientist","departament":"Support","date":"06/01/2020"},
{"id":6,"name":"Dynah","surname":"Sturm","position":"Office Assistant I","departament":"Marketing","date":"08/08/2019"},
{"id":7,"name":"Jude","surname":"Levington","position":"Environmental Specialist","departament":"Research and Development","date":"05/11/2018"},
{"id":8,"name":"Tera","surname":"Ellis","position":"Marketing Assistant","departament":"Legal","date":"21/05/2021"},
{"id":9,"name":"Noach","surname":"Malmar","position":"Senior Cost Accountant","departament":"Human Resources","date":"16/05/2020"},
{"id":10,"name":"Darby","surname":"Squirrel","position":"Software Test Engineer IV","departament":"Human Resources","date":"05/06/2019"},
{"id":11,"name":"Coralie","surname":"Greschik","position":"Cost Accountant","departament":"Legal","date":"12/10/2020"},
{"id":12,"name":"Jeannie","surname":"Emanulsson","position":"VP Product Management","departament":"Services","date":"19/11/2019"},
{"id":13,"name":"Kennie","surname":"Ughetti","position":"Accountant II","departament":"Support","date":"11/02/2021"},
{"id":14,"name":"Ricoriki","surname":"Ringe","position":"Human Resources Manager","departament":"Human Resources","date":"16/12/2020"},
{"id":15,"name":"Sloane","surname":"Yelland","position":"Programmer II","departament":"Human Resources","date":"29/08/2019"},
{"id":16,"name":"Brandtr","surname":"Wearn","position":"Help Desk Operator","departament":"Marketing","date":"01/12/2018"},
{"id":17,"name":"Cleve","surname":"Key","position":"Analyst Programmer","departament":"Services","date":"11/12/2018"},
{"id":18,"name":"Susan","surname":"Baiss","position":"Database Administrator III","departament":"Human Resources","date":"03/07/2020"},
{"id":19,"name":"Blaine","surname":"Lennon","position":"Administrative Assistant IV","departament":"Accounting","date":"18/03/2020"},
{"id":20,"name":"Neala","surname":"Clendinning","position":"Research Associate","departament":"Sales","date":"30/03/2021"},
{"id":21,"name":"Rebe","surname":"Tutill","position":"Statistician I","departament":"Marketing","date":"28/09/2019"},
{"id":22,"name":"Lilia","surname":"Peirson","position":"Automation Specialist I","departament":"Product Management","date":"17/07/2020"},
{"id":23,"name":"Anabel","surname":"Demonge","position":"Accountant III","departament":"Marketing","date":"12/06/2019"},
{"id":24,"name":"Koenraad","surname":"Ainsworth","position":"General Manager","departament":"Support","date":"10/02/2019"},
{"id":25,"name":"Somerset","surname":"Treffrey","position":"Office Assistant I","departament":"Services","date":"24/01/2020"},
{"id":26,"name":"Cammy","surname":"Scrogges","position":"Staff Scientist","departament":"Research and Development","date":"11/07/2020"},
{"id":27,"name":"Bert","surname":"Gyorgy","position":"Occupational Therapist","departament":"Engineering","date":"01/07/2020"},
{"id":28,"name":"Rebeca","surname":"Skeermor","position":"Nuclear Power Engineer","departament":"Business Development","date":"21/03/2020"},
{"id":29,"name":"Shawnee","surname":"Whapple","position":"Biostatistician III","departament":"Research and Development","date":"08/02/2019"},
{"id":30,"name":"Gothart","surname":"Duthy","position":"Web Developer I","departament":"Engineering","date":"18/11/2019"},
{"id":31,"name":"Sherman","surname":"Gilyatt","position":"Pharmacist","departament":"Accounting","date":"15/03/2019"},
{"id":32,"name":"Perceval","surname":"Parcall","position":"Media Manager IV","departament":"Business Development","date":"22/09/2018"},
{"id":33,"name":"Renell","surname":"Klausen","position":"Tax Accountant","departament":"Product Management","date":"08/07/2020"},
{"id":34,"name":"Anderson","surname":"Calkin","position":"Pharmacist","departament":"Product Management","date":"29/04/2019"},
{"id":35,"name":"Merrill","surname":"Nellis","position":"Budget/Accounting Analyst II","departament":"Legal","date":"30/06/2019"},
{"id":36,"name":"Minetta","surname":"Gilvary","position":"Community Outreach Specialist","departament":"Human Resources","date":"16/09/2020"},
{"id":37,"name":"Carlos","surname":"Biss","position":"Account Executive","departament":"Sales","date":"11/09/2019"},
{"id":38,"name":"Jewelle","surname":"Sign","position":"Information Systems Manager","departament":"Business Development","date":"28/05/2020"},
{"id":39,"name":"Lilith","surname":"Breadon","position":"Quality Control Specialist","departament":"Marketing","date":"14/05/2019"},
{"id":40,"name":"Elsey","surname":"Haxbie","position":"Quality Engineer","departament":"Human Resources","date":"20/12/2020"},
{"id":41,"name":"Wyn","surname":"Nutkin","position":"VP Marketing","departament":"Product Management","date":"16/04/2020"},
{"id":42,"name":"Vanessa","surname":"Privost","position":"VP Accounting","departament":"Research and Development","date":"24/08/2020"},
{"id":43,"name":"Tadeas","surname":"Morrice","position":"Sales Associate","departament":"Training","date":"03/07/2019"},
{"id":44,"name":"Phillida","surname":"Alonso","position":"Recruiting Manager","departament":"Sales","date":"06/03/2019"},
{"id":45,"name":"Piggy","surname":"Glede","position":"Senior Quality Engineer","departament":"Research and Development","date":"29/09/2019"},
{"id":46,"name":"Yolane","surname":"Strafford","position":"Associate Professor","departament":"Accounting","date":"20/01/2020"},
{"id":47,"name":"Guillermo","surname":"Boyda","position":"Compensation Analyst","departament":"Engineering","date":"10/02/2020"},
{"id":48,"name":"Alphonso","surname":"Goulbourne","position":"Software Consultant","departament":"Business Development","date":"05/10/2020"},
{"id":49,"name":"Dee","surname":"Brasse","position":"General Manager","departament":"Services","date":"30/12/2018"},
{"id":50,"name":"Fin","surname":"Widmore","position":"VP Product Management","departament":"Training","date":"29/10/2020"}]